<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($user) {
            $userRole = Role::role('user')->first();
            $user->roles()->attach($userRole->id);
        });
    }

    public function posts() {
        return $this->hasMany(Post::class, 'author_id');
    }

    public function roles() {
        return $this->belongsToMany(Role::class);
    }

    public function hasRole($roleName) {
        $role = Role::role($roleName)->first();

        return $this->roles->contains($role->id);
    }

}
